apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
stringData:
  access_key: "${AWS_ACCESS_KEY_ID}"
  secret_key: "${AWS_SECRET_ACCESS_KEY}"
---
apiVersion: v1
kind: Secret
metadata:
  name: rds-credentials
type: Opaque
stringData:
  db_name: "${RDS_DB_NAME}"
  db_host: "${RDS_HOST}"
  db_user: "${RDS_USERNAME}"
  db_password: "${RDS_PASSWORD}"
