- name: Apply Kubernetes manifests
  hosts: master
  become: yes

  vars:
    project_dir: /home/user1/project

  tasks:
    - name: Apply Secret
      shell: kubectl apply -f {{ project_dir }}/k8s/secret.yaml

    - name: Apply Service
      shell: kubectl apply -f {{ project_dir }}/k8s/service.yaml

    - name: Apply Deployment
      shell: kubectl apply -f {{ project_dir }}/k8s/deployment.yaml
