name: Deploy Nextcloud

on:
  push:
    branches: [ main ]  # main 브랜치에 푸시 시 실행
  workflow_dispatch:    # 수동 실행 허용

env:
  NEXTCLOUD_VERSION: "31.0.5.1"  # 사용할 Nextcloud 버전

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Docker 빌드
      - name: Build Docker image
        run: |
          docker build -t nextcloud-custom .

      # 3. RDS 연결 테스트 (선택 사항)
      - name: Verify RDS connection
        run: |
          docker run --rm \
            -e RDS_HOST=${{ secrets.RDS_HOST }} \
            -e RDS_DB_NAME=${{ secrets.RDS_DB_NAME }} \
            -e RDS_USERNAME=${{ secrets.RDS_USERNAME }} \
            -e RDS_PASSWORD=${{ secrets.RDS_PASSWORD }} \
            nextcloud-custom \
            bash -c "apt-get update && apt-get install -y mysql-client && \
            mysql -h $RDS_HOST -u $RDS_USERNAME -p$RDS_PASSWORD -e 'SHOW DATABASES;'"

      # 4. Nextcloud 설치
      - name: Install Nextcloud
        run: |
          docker run --rm \
            -e RDS_HOST=${{ secrets.RDS_HOST }} \
            -e RDS_DB_NAME=${{ secrets.RDS_DB_NAME }} \
            -e RDS_USERNAME=${{ secrets.RDS_USERNAME }} \
            -e RDS_PASSWORD=${{ secrets.RDS_PASSWORD }} \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            nextcloud-custom \
            sh -c "php occ maintenance:install \
              --database=mysql \
              --database-host=\"$RDS_HOST\" \
              --database-name=\"$RDS_DB_NAME\" \
              --database-user=\"$RDS_USERNAME\" \
              --database-pass=\"$RDS_PASSWORD\" \
              --admin-user=\"admin\" \
              --admin-pass=\"${{ secrets.NEXTCLOUD_ADMIN_PASSWORD }}\""
