name: Deploy Nextcloud

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  NEXTCLOUD_VERSION: "31.0.5.1"
  DOCKER_IMAGE: "nextcloud-custom"  # Docker 이미지 이름 변수화

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Docker 로그인 (프라이빗 레지스트리 사용 시)
      - name: Login to Docker Hub
        if: env.DOCKER_HUB_TOKEN != ''  # 조건부 실행
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # 3. Docker 빌드 (캐시 활용)
      - name: Build Docker image
        run: |
          docker build \
            --tag $DOCKER_IMAGE:${{ github.sha }} \  # 고유 태그 추가
            --tag $DOCKER_IMAGE:latest .

      # 4. RDS 연결 테스트 (실패 시 자동 종료)
      - name: Verify RDS connection
        run: |
          docker run --rm \
            -e RDS_HOST=${{ secrets.RDS_HOST }} \
            -e RDS_DB_NAME=${{ secrets.RDS_DB_NAME }} \
            -e RDS_USERNAME=${{ secrets.RDS_USERNAME }} \
            -e RDS_PASSWORD=${{ secrets.RDS_PASSWORD }} \
            $DOCKER_IMAGE:${{ github.sha }} \
            bash -c "apt-get update && \
            apt-get install -y mysql-client && \
            mysql -h $RDS_HOST -u $RDS_USERNAME -p$RDS_PASSWORD \
              -e 'CREATE DATABASE IF NOT EXISTS $RDS_DB_NAME; SHOW DATABASES;'"

      # 5. Nextcloud 설치 (의존성 캐시 활용)
      - name: Install Nextcloud
        run: |
          docker run --rm \
            -v nextcloud-data:/var/www/html/data \  # 영구 볼륨 마운트
            -e RDS_HOST=${{ secrets.RDS_HOST }} \
            -e RDS_DB_NAME=${{ secrets.RDS_DB_NAME }} \
            -e RDS_USERNAME=${{ secrets.RDS_USERNAME }} \
            -e RDS_PASSWORD=${{ secrets.RDS_PASSWORD }} \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            $DOCKER_IMAGE:${{ github.sha }} \
            sh -c "php occ maintenance:install \
              --database=mysql \
              --database-host=\"$RDS_HOST\" \
              --database-name=\"$RDS_DB_NAME\" \
              --database-user=\"$RDS_USERNAME\" \
              --database-pass=\"$RDS_PASSWORD\" \
              --admin-user=\"admin\" \
              --admin-pass=\"${{ secrets.NEXTCLOUD_ADMIN_PASSWORD }}\" && \
              php occ config:system:set trusted_domains 1 --value='${{ vars.DOMAIN }}'"

      # 6. 건강 상태 확인 (선택 사항)
      - name: Health check
        run: |
          curl -sSf http://localhost/status.php | grep -q '"installed":true'
