name: Deploy Nextcloud to Kubernetes

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  NEXTCLOUD_VERSION: "31.0.5.1"
  AWS_REGION: "ap-northeast-2"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 레포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Docker 이미지 빌드
      - name: Build Docker image
        run: |
          docker build -t nextcloud-s3:${{ github.sha }} .

      # 3. kubeconfig 셋업
      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_B64 }}" | base64 --decode > ~/.kube/config

      # 4. (선택) 이미지 푸시
      - name: Push Docker image to registry
        # if: secrets.REGISTRY_USERNAME
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin
          docker tag nextcloud-s3:${{ github.sha }} parkkyungin/nextcloud:${{ github.sha }}
          docker push parkkyungin/nextcloud:${{ github.sha }}
          
          
      # 5. 쿠버네티스에 배포
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

          
      ## 3. RDS/S3 연결 테스트
      #- name: Verify infrastructure
      #  run: |
      #    docker run --rm \
      #      -e RDS_HOST=${{ secrets.RDS_HOST }} \
      #      -e RDS_DB_NAME=${{ secrets.RDS_DB_NAME }} \
      #      -e RDS_USERNAME=${{ secrets.RDS_USERNAME }} \
      #      -e RDS_PASSWORD=${{ secrets.RDS_PASSWORD }} \
      #      -e S3_BUCKET=${{ secrets.S3_BUCKET }} \
      #      -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
      #      -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
      #      -e AWS_REGION=${{ env.AWS_REGION }} \
      #      nextcloud-s3:${{ github.sha }} \
      #      bash -c '
      #        apt-get update && \
      #        mysql -h "$RDS_HOST" -u "$RDS_USERNAME" -p"$RDS_PASSWORD" -e "SHOW DATABASES;" && \
      #        aws s3 ls "s3://$S3_BUCKET" || aws s3 mb "s3://$S3_BUCKET" --region $AWS_REGION
      #      '

      ## 4. Nextcloud 설치
      #- name: Install Nextcloud
      #  run: |
      #    docker run --rm \
      #      -e RDS_HOST=${{ secrets.RDS_HOST }} \
      #      -e RDS_DB_NAME=${{ secrets.RDS_DB_NAME }} \
      #      -e RDS_USERNAME=${{ secrets.RDS_USERNAME }} \
      #      -e RDS_PASSWORD=${{ secrets.RDS_PASSWORD }} \
      #      -e S3_BUCKET=${{ secrets.S3_BUCKET }} \
      #      -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
      #      -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
      #      -w /var/www/html \
      #      nextcloud-s3:${{ github.sha }} \
      #      sh -c "php occ maintenance:install \
      #        --database=mysql \
      #        --database-host=\"$RDS_HOST\" \
      #        --database-name=\"$RDS_DB_NAME\" \
      #        --database-user=\"$RDS_USERNAME\" \
      #        --database-pass=\"$RDS_PASSWORD\" \
      #        --admin-user=\"admin\" \
      #        --admin-pass=\"${{ secrets.NEXTCLOUD_ADMIN_PASSWORD }}\""

