name: Deploy Nextcloud to Kubernetes

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  NEXTCLOUD_VERSION: "31.0.5.1"
  AWS_REGION: "ap-northeast-2"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t nextcloud-s3:${{ github.sha }} .
          docker tag nextcloud-s3:${{ github.sha }} ${{ secrets.REGISTRY_USERNAME }}/nextcloud:${{ github.sha }}

      - name: Log in and push to Docker Hub
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin
          docker push ${{ secrets.REGISTRY_USERNAME }}/nextcloud:${{ github.sha }}



  deploy-to-cluster:
    runs-on: self-hosted
    needs: build-and-push  # 이 줄이 중요! 먼저 build-and-push가 끝난 뒤 실행됨

    steps:
      - name: Render and apply Kubernetes Secrets
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          RDS_DB_NAME: ${{ secrets.RDS_DB_NAME }}
          RDS_HOST: ${{ secrets.RDS_HOST }}
          RDS_USERNAME: ${{ secrets.RDS_USERNAME }}
          RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
        run: |
          envsubst '${AWS_ACCESS_KEY_ID} ${AWS_SECRET_ACCESS_KEY} ${RDS_DB_NAME} ${RDS_HOST} ${RDS_USERNAME} ${RDS_PASSWORD}' \
            < k8s/secret-template.yaml > k8s/secret.yaml
          kubectl apply -f k8s/secret.yaml
          
      - name: Clone project repo
        run: git clone https://github.com/parkkyungin/project

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ./project/k8s/deployment.yaml
          kubectl apply -f ./project/k8s/service.yaml
