name: Test RDS Connection

on:
  #push:
  #  branches: [ main ]
  workflow_dispatch:
jobs:
  test-rds:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # 1. 코드 가져오기

    - name: Debug Secrets
      run: |
        echo "RDS_HOST: ${{ secrets.RDS_HOST }}"
        echo "RDS_USER: ${{ secrets.RDS_USERNAME }}"
        # 비밀번호는 로그에 출력되지 않음
      env:
        RDS_HOST: ${{ secrets.RDS_HOST }}
        RDS_USERNAME: ${{ secrets.RDS_USERNAME }}

    - name: Test MySQL Connection
      run: |
        # 2. mysql-client 설치
        sudo apt-get update && sudo apt-get install -y mysql-client

        # 3. RDS 연결 테스트 (간단한 쿼리 실행)
        mysql -h ${{ secrets.RDS_HOST }} \
              -u ${{ secrets.RDS_USERNAME }} \
              -p${{ secrets.RDS_PASSWORD }} \
              -e "SHOW DATABASES;"
